apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
bases:
  - ../base/
configMapGenerator:
- name: fluent-bit-config
  behavior: merge
  files:
  - output-postgresql.conf
