apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - namespace.yaml
  - fluent-bit-service-account.yaml
  - fluent-bit-role.yaml
  - fluent-bit-role-binding.yaml
  - fluent-bit-ds.yaml
  - fluent-bit-configmap.yaml
